#define FALSE 0
#define TRUE 1

#define WINDOW_WIDTH 800
#define WINDOW_HEIGHT 600

#define PONG_BALL_RADIUS 10
#define PONG_BALL_PIXELS_PER_SECOND_X 60
#define PONG_BALL_PIXELS_PER_SECOND_Y 40

#define PADDLE_WIDTH 7
#define PADDLE_HEIGHT 60
#define PADDLE_DISTANCE_FROM_BORDER 10
#define PADDLE_PIXEL_PER_SECOND 600

#define CENTRE_RECTANGLE_WIDTH 8
#define CENTRE_RECTANGLE_HEIGHT 18
#define CENTRE_RECTANGLE_GAP 10

#define FPS 100
#define FRAME_TARGET_TIME (1000 / FPS)