#define FALSE 0
#define TRUE 1

#define WINDOW_WIDTH 800
#define WINDOW_HEIGHT 600

#define PONG_BALL_RADIUS 10
#define PONG_BALL_SPEED_PER_SECOND 70

#define PADDLE_WIDTH 7
#define PADDLE_HEIGHT 60
#define PADDLE_DISTANCE_FROM_BORDER 10
#define PADDLE_SPEED_PER_SECOND 600

#define FPS 60
#define FRAME_TARGET_TIME (1000 / FPS)